name: Generate GitHub Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: markjacksonfishing
          template: classic
          base: header, activity
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full  # Set duration to 'full' here
          config_timezone: America/Los_Angeles
          filename: metrics.svg
